config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/invoices'

  resources :invoices

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end

  def show
    @invoice = Invoice.find(params[:id])
  end
   
  def new
  end

  def create
    @invoice = Invoice.new(invoice_params)

    @invoice.save
    redirect_to @invoice
  end

  private
    def invoice_params
      params.require(:invoice).permit(:invoicenumber, :companyname, :manager, :dategenerated, :paid, :amountdue, :terms, :accountmanager)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def invoices
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/invoices/index.html.erb
<h1>Listing of Invoices</h1>

<table>
	<tr>
		<th>Invoice Number</th>
		<th>Company Name</th>
		<th>Manager</th>
		<th>Date Generated</th>
		<th>Paid</th>
		<th>Amount Due</th>
		<th>Terms</th>
		<th>Account Manager</th>
	</tr>

	<% @invoices.each do |invoice| %>
		<tr>
			<td><%= invoice.invoicenumber %></td>
			<td><%= invoice.companyname %></td>
			<td><%= invoice.manager %></td>
			<td><%= invoice.dategenerated %></td>
			<td><%= invoice.paid %></td>
			<td><%= invoice.amountdue %></td>
			<td><%= invoice.terms %></td>
			<td><%= invoice.accountmanager %></td>
			<td><%= link_to 'Show', invoice_path(invoice) %></td>
		</tr>
	<% end %>
</table>
 

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= form_with scope: :invoice, url: invoices_path, local: true do |form| %>
	<p>
		<%= form.label :invoicenumber %><br>
		<%= form.text_field :invoicenumber %>
	</p>

	<p>
		<%= form.label :companyname %><br>
		<%= form.text_field :companyname %>
	</p>

	<p>
		<%= form.label :manager %><br>
		<%= form.text_field :manager %>
	</p>

	<p>
		<%= form.label :dategenerated %><br>
		<%= form.date_field :dategenerated %>
	</p>

	<p>
		<%= form.label :paid %><br>
		<%= form.text_field :paid %>
	</p>

	<p>
		<%= form.label :amountdue %><br>
		<%= form.number_field :amountdue %>
	</p>

	<p>
		<%= form.label :terms %><br>
		<%= form.text_area :terms %>
	</p>

	<p>
		<%= form.label :accountmanager %><br>
		<%= form.text_field :accountmanager %>
	</p>

	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/invoices/show.html.erb
<h1>Invoice Detail</h1>

	<p>
		<strong>Invoice Number</strong>
		<%= @invoice.invoicenumber %>
	</p>

	<p>
		<strong>Company Name</strong>
		<%= @invoice.companyname %>
	</p>

	<p>
		<strong>Manager</strong>
		<%= @invoice.manager %>
	</p>

	<p>
		<strong>Date Generated</strong>
		<%= @invoice.dategenerated %>
	</p>

	<p>
		<strong>Paid</strong>
		<%= @invoice.paid %>
	</p>

	<p>
		<strong>Amount Due</strong>
		<%= @invoice.amountdue %>
	</p>

	<p>
		<strong>Terms</strong>
		<%= @invoice.terms %>
	</p>

	<p>
		<strong>Account Manager</strong>
		<%= @invoice.accountmanager %>
	</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoiceupload</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/invoices.html.erb
<h1>Invoices</h1>